#include <hwtHls/llvm/Transforms/LoopFlattenUsingIfPass.h>

#include <algorithm>
#include <map>
#include <limits>

#include <llvm/Analysis/AssumptionCache.h>
#include <llvm/Analysis/DomTreeUpdater.h>
#include <llvm/Analysis/InstructionSimplify.h>
#include <llvm/Analysis/LazyBlockFrequencyInfo.h>
#include <llvm/Analysis/LoopInfo.h>
#include <llvm/Analysis/LoopPass.h>
#include <llvm/Analysis/MemorySSA.h>
#include <llvm/Analysis/MemorySSAUpdater.h>
#include <llvm/Analysis/OptimizationRemarkEmitter.h>
#include <llvm/Analysis/ScalarEvolution.h>
#include <llvm/Analysis/TargetTransformInfo.h>
#include <llvm/InitializePasses.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/Verifier.h>
#include <llvm/Support/CommandLine.h>
#include <llvm/Transforms/Scalar.h>
#include <llvm/Transforms/Scalar/LoopPassManager.h>
#include <llvm/Transforms/Utils/BasicBlockUtils.h>
#include <llvm/Transforms/Utils/PromoteMemToReg.h>

#include <hwtHls/llvm/Transforms/HwtHlsSimplifyCFGPass/HwtHlsSimplifyCFGUtils.h>
#include <hwtHls/llvm/Transforms/utils/inLoopConditionalExecution.h>
#include <hwtHls/llvm/Transforms/utils/loopMerging.h>
#include <hwtHls/llvm/Transforms/utils/loopHwtHlsMetadata.h>
#include <hwtHls/llvm/Transforms/LoopFlattenUsingIfPass/findAssociatedPhis.h>
#include <hwtHls/llvm/Transforms/LoopFlattenUsingIfPass/mergeLoopMetadata.h>
#include <hwtHls/llvm/Transforms/LoopFlattenUsingIfPass/rerouteChildBackedgeAndTransferChildPhis.h>

// #define LoopFlattenUsingIfPass_TRACE

#ifdef LoopFlattenUsingIfPass_TRACE
#include <hwtHls/llvm/Transforms/utils/writeCFGToDotFile.h>
#endif

using namespace llvm;

#define DEBUG_TYPE "loop-flatten-usingif"

namespace hwtHls {

#ifdef LoopFlattenUsingIfPass_TRACE
static size_t dbgCntr = 0;
#endif

const std::string LoopFlattenUsingIfPass::METADATANAME_MODE =
		"hwthls.loop.flattenusingif.mode";

LoopFlattenUsingIfPass::Mode LoopFlattenUsingIfPass::modeStringToMode(
		const llvm::StringRef mode) {
	if (mode == "CHILD_LOOP_ENTRY_IN_SAME_ITERATION")
		return CHILD_LOOP_ENTRY_IN_SAME_ITERATION;
	else if (mode == "CHILD_LOOP_ENTRY_IN_NEXT_ITERATION")
		return CHILD_LOOP_ENTRY_IN_NEXT_ITERATION;
	else {
		llvm_unreachable(
				(std::string("unsupported value for LoopFlattenUsingIfPass::Mode: ") + mode).c_str());
	}
	return CHILD_LOOP_ENTRY_IN_SAME_ITERATION;
}

static PHINode* createIsChildLoopPhiInHeader(
		llvm::LoopStandardAnalysisResults &AR, DomTreeUpdater &DTU,
		MemorySSAUpdater *MSSAU, llvm::Loop &LParent, llvm::Loop &LChild,
		BasicBlock *header, BasicBlock *childHeader) {
	auto &Ctx = header->getContext();
	auto int1Ty = IntegerType::getInt1Ty(Ctx);
	auto *isChildLoop = PHINode::Create(int1Ty,
			pred_size(header) + pred_size(childHeader),
			"isChildLoop." + childHeader->getName(), header->begin());
	for (auto pred : predecessors(header)) {
		if (!LParent.contains(pred))
			isChildLoop->addIncoming(ConstantInt::get(int1Ty, 0), pred);
	}
	for (auto *childHeadPred : make_early_inc_range(predecessors(childHeader))) {
		if (childHeadPred == header
				|| llvm::any_of(predecessors(header),
						[childHeadPred](BasicBlock *BB) {
							return BB == childHeadPred;
						})) {
			// if it was already a successor create a new block for current exitBB, because of PHIs
			// :note: LoopSimplify normal form requires preheader but preheader may still be parent header
			if (DTU.hasPendingUpdates())
				DTU.flush();
			CriticalEdgeSplittingOptions Options(
					DTU.hasDomTree() ? &DTU.getDomTree() : nullptr, &AR.LI,
					MSSAU,
					DTU.hasPostDomTree() ? &DTU.getPostDomTree() : nullptr);
			childHeadPred = SplitCriticalEdge(childHeadPred, childHeader,
					Options);
			if (DTU.hasPendingUpdates())
				DTU.flush();

		} else {
			assert(
					(LChild.contains(childHeadPred)
							|| LParent.contains(childHeadPred)));
		}
	}
	return isChildLoop;
}

static void collectBlocksUntilSrcBlock(BasicBlock &untilBlock,
		SetVector<BasicBlock*> &seen, BasicBlock &current) {
	if (&current == &untilBlock || seen.contains(&current))
		return;
	seen.insert(&current);
	for (auto *pred : predecessors(&current)) {
		collectBlocksUntilSrcBlock(untilBlock, seen, *pred);
	}
}

/*
 * :param phiInLatchDrivingBranch: phi generated by this function which is resolved whenver
 *    the merged loop should exit or not.
 * :param valueForPhiInLatchCausingReenter: the value resolved by this function,
 *    if the phiInLatchDrivingBranch will have this value the code will jump out of merged loop
 * */
static std::pair<BasicBlock*, BasicBlock*> prepareNewLatchBlock(
		LoopFlattenUsingIfPass::Mode mode, llvm::Loop &LParent,
		DomTreeUpdater &DTU, llvm::LoopStandardAnalysisResults &AR,
		MemorySSAUpdater *MSSAU, PHINode *&phiInLatchDrivingBranch,
		Value *&valueForPhiInLatchCausingReenter, BasicBlock *header,
		BasicBlock *childPreHeader) {
	BasicBlock *oldLatchBlock = LParent.getLoopLatch();
	BasicBlock *newLatchBlock = oldLatchBlock;

	auto &Ctx = header->getContext();
	auto int1Ty = IntegerType::getInt1Ty(Ctx);

	assert(
			newLatchBlock
					&& "Must be present because this is in LoopSimplify normal form");
	Instruction *Term = oldLatchBlock->getTerminator();
	assert(Term);

	//if (BR && !BR->isConditional()
	//		&& (Term == &*oldLatchBlock->begin()
	//				|| isa<PHINode>(Term->getPrevNode()))) {
	// :note: this does not work because it would not be possible to recognize if we
	//       jumped from
	//	// block contains only PHIs and terminator
	//	// we can reuse this block because it has unconditional branch
	//  return {newLatchBlock, oldLatchBlock};
	//}

	if (DTU.hasPendingUpdates()) {
		DTU.flush();
	}
#ifdef LoopFlattenUsingIfPass_TRACE
	assert(DTU.getDomTree().verify());
	//if (MSSAU)
	//	MSSAU->getMemorySSA()->verifyMemorySSA(
	//			MemorySSA::VerificationLevel::Full);
#endif
	oldLatchBlock = SplitBlock(oldLatchBlock, Term, &DTU, &AR.LI, MSSAU,
			oldLatchBlock->getName() + ".oldLatch", /*Before*/
			true);

	if (DTU.hasPendingUpdates()) {
		DTU.flush();
	}
	size_t phiArgCnt =
			2
					+ (mode
							== LoopFlattenUsingIfPass::Mode::CHILD_LOOP_ENTRY_IN_NEXT_ITERATION);
	if (auto BR = dyn_cast<BranchInst>(Term)) {
		if (BR->isConditional()) {
			phiInLatchDrivingBranch = PHINode::Create(int1Ty, phiArgCnt,
					"fusedLoopContinueFromBr", newLatchBlock->begin());
			phiInLatchDrivingBranch->addIncoming(BR->getCondition(),
					oldLatchBlock);

			BR->setCondition(phiInLatchDrivingBranch);
			// reenter (the loop exits and it may be reentered) is when successor is not header
			auto _loopExitOrReenterVal = ConstantInt::get(int1Ty,
					BR->getSuccessor(0) == header);
			valueForPhiInLatchCausingReenter = _loopExitOrReenterVal;
			if (mode
					== LoopFlattenUsingIfPass::Mode::CHILD_LOOP_ENTRY_IN_NEXT_ITERATION) {
				// addIncoming for every child loop preheader which will not cause break
				phiInLatchDrivingBranch->addIncoming(
						ConstantInt::get(int1Ty, ~_loopExitOrReenterVal->getValue()),
						childPreHeader);
			}
		} else {
			// no need to resolve valueForPhiInLatchCausingReenter
			// the SplitBlock was called to separate non-phi instructions to other block
		}
	} else if (SwitchInst *SW = dyn_cast<SwitchInst>(Term)) {
		auto Cond = SW->getCondition();
		phiInLatchDrivingBranch = PHINode::Create(Cond->getType(), 2,
				"fusedLoopContinueFromSw", newLatchBlock->begin());
		phiInLatchDrivingBranch->addIncoming(Cond, oldLatchBlock);
		BR->setCondition(phiInLatchDrivingBranch);
		for (auto &SwCase : SW->cases()) {
			if (SwCase.getCaseSuccessor() == header) {
				valueForPhiInLatchCausingReenter = SwCase.getCaseValue();
				break;
			}
		}
		if (!valueForPhiInLatchCausingReenter)
			llvm_unreachable(
					"NotImplemented: backedge is switch default branch, need to infer value for condition");
		if (mode
				== LoopFlattenUsingIfPass::Mode::CHILD_LOOP_ENTRY_IN_NEXT_ITERATION) {
			llvm_unreachable(
					"NotImplemented: addIncoming for every child loop preheader which will not cause break");
		}
	} else {
		Term->dump();
		llvm_unreachable("Unsupported type of terminator");
	}
	return {newLatchBlock, oldLatchBlock};
}

//void promoteAllocasForBeginSectionLiveouts(BasicBlock *beginSectionBegin,
//		BasicBlock *beginSectionEnd, llvm::Loop &LParent, DomTreeUpdater &DTU,
//		llvm::LoopStandardAnalysisResults &AR) {
//	// handle lifetime of variables defined in begin section (they are alive during iteration of child loop,
//	// and now they are alive also during parent loop)
//	// rm Intrinsic::lifetime_start
//	for (auto &I : make_early_inc_range(*beginSectionBegin)) {
//		if (isa<PHINode>(&I)) {
//		} else if (auto C = dyn_cast<CallInst>(&I)) {
//			if (C->getCalledFunction()->getIntrinsicID()
//					== Intrinsic::lifetime_start) {
//				C->eraseFromParent();
//			}
//		} else {
//			break;
//		}
//	}
//	// move all Intrinsic::lifetime_end to exits of parent loop
//	// (lifetime_ends are at the end of the block just before terminator)
//	Instruction *lifetime_end_begin = nullptr;
//	Instruction *lifetime_end_end = beginSectionEnd->getTerminator();
//	if (lifetime_end_end != &*beginSectionEnd->begin()) {
//		for (auto *I = lifetime_end_end->getPrevNode();
//				I != &*beginSectionEnd->begin(); I = I->getPrevNode()) {
//			if (auto C = dyn_cast<CallInst>(I)) {
//				if (C->getCalledFunction()->getIntrinsicID()
//						== Intrinsic::lifetime_end) {
//					lifetime_end_begin = I;
//					continue;
//				}
//			}
//			break;
//		}
//		if (lifetime_end_begin) {
//			SmallVector<BasicBlock*> ExitBlocks;
//			LParent.getUniqueExitBlocks(ExitBlocks);
//			auto lifemtime_ends = make_range(lifetime_end_begin->getIterator(),
//					lifetime_end_end->getIterator());
//			SmallVector<AllocaInst*> Allocas;
//			for (Instruction &I : lifemtime_ends) {
//				auto C = dyn_cast<CallInst>(&I);
//				assert(C);
//				auto A = dyn_cast<AllocaInst>(C->getArgOperand(1));
//				assert(A);
//				Allocas.push_back(A);
//			}
//			for (auto exit : ExitBlocks) {
//				// copy Intrinsic::lifetime_end after phis
//				auto insertPoint = exit->getFirstNonPHI();
//				for (Instruction &I : lifemtime_ends) {
//					auto newI = I.clone();
//					newI->insertBefore(insertPoint);
//				}
//			}
//			// remove Intrinsic::lifetime_end from beginSectionEnd
//			for (Instruction &I : make_early_inc_range(lifemtime_ends)) {
//				I.eraseFromParent();
//			}
//			if (DTU.hasPendingUpdates())
//				DTU.flush();
//
//			// construct PHIs for variables defined in loop begin section which are now alive trough iteration
//			// of parent loop because it was merged with child loop
//			PromoteMemToReg(Allocas, DTU.getDomTree(), &AR.AC);
//		}
//	}
//}


static bool LoopFlattenUsingIfPass_flatten(const LoopFlattenUsingIfPass::Mode mode, llvm::Loop &LParent,
		llvm::Loop &LChild, llvm::LoopStandardAnalysisResults &AR,
		DomTreeUpdater &DTU, MemorySSAUpdater *MSSAU, llvm::LPMUpdater &LPMU) {
	{
		auto *F = LParent.getHeader()->getParent();
		using namespace ore;
		OptimizationRemark Remark(DEBUG_TYPE, "FlattenedUsingIf",
				LChild.getStartLoc(), LChild.getHeader());
		OptimizationRemarkEmitter ORE(F, AR.BFI);
		Remark << "Flattened using \"if\" into outer loop";
		ORE.emit(Remark);
	}

	bool Changed = false;
#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++)
					+ "-start.dot", AR.BFI, AR.BPI);
#endif
	auto associatedPhis = findAssociatedPhis(LParent, LChild);

	BasicBlock *header = LParent.getHeader();
	BasicBlock *childPreHeader = LChild.getLoopPreheader();
	BasicBlock *childHeader = LChild.getHeader();
	auto *isChildLoop = createIsChildLoopPhiInHeader(AR, DTU, MSSAU, LParent,
			LChild, header, childHeader);

	auto headerPhisEnd = header->getFirstNonPHIIt();
	//IRBuilder<> Builder(headerPhisEnd);
	// create if (!isChildLoop) sectionFromParentHeaderToChildHeader();
	BasicBlock *loopBegin = SplitBlock(header, headerPhisEnd, &DTU, &AR.LI,
			MSSAU);
	if (header == childPreHeader)
		childPreHeader = loopBegin;

#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++)
					+ "-after-initNormalization.dot", AR.BFI, AR.BPI);
	DTU.flush();
	assert(DTU.getDomTree().verify());
	if (MSSAU) {
		MSSAU->getMemorySSA()->verifyMemorySSA(
				MemorySSA::VerificationLevel::Full);
	}
#endif

	// Blocks reachable from child loop header until parent loop header;
	SetVector<BasicBlock*> parenLoopBeginBlocks;
	// because the top most block must be the first
	parenLoopBeginBlocks.insert(loopBegin);
	for (auto pred : predecessors(childHeader)) {
		if (!LChild.contains(pred))
			collectBlocksUntilSrcBlock(*header, parenLoopBeginBlocks, *pred);
	}
#ifdef LoopFlattenUsingIfPass_TRACE
	DTU.flush();
	assert(DTU.getDomTree().verify());
	if (MSSAU) {
		MSSAU->getMemorySSA()->verifyMemorySSA(
				MemorySSA::VerificationLevel::Full);
	}
#endif

	//BasicBlock *beginSectionBegin;
	//BasicBlock *beginSectionEnd;
	//std::tie(beginSectionBegin, beginSectionEnd) =
	auto tmpAllocas = makeSectionOfLoopConditionalyReexecuted(LParent, header,
			childHeader, parenLoopBeginBlocks, isChildLoop, DTU, AR.LI, MSSAU,
			AR.BFI, AR.BPI, &AR.AC, /*conditionIsNegated*/true);
#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++)
					+ "-after-makeSectionOfLoopConditionalyReexecuted.dot",
			AR.BFI, AR.BPI);
	DTU.flush();
	assert(DTU.getDomTree().verify());
	if (MSSAU) {
		MSSAU->getMemorySSA()->verifyMemorySSA(
				MemorySSA::VerificationLevel::Full);
	}
#endif

	// :note: LoopSimplify normal form requires that there is a single backedge and latch block
	// :note: LCSSA pass transforms loops by placing phi nodes at the end of the loops for
	//   all values that are live across the loop boundary (and defined in the loop)
	// :note: The liveins and liveouts of child loop which are defined in parent loop needs to have a phi in new header
	//   which switches the value previously defined value defined in the parent loop begin and undef if this is a first iteration.
	// :note: liveouts are noted in PHIs created by LCSSA on every exit block, liveins are in PHIs of child block
	//   plus uses in child loop which are defined in parent loop

	// Cases which needs to be handled when rerouting child loop:
	// * value is defined in parent begin (which can be skipped) and is used in parent end
	//    * A tmp phi must be created in header to hold the value during iterations of child loop
	//    * There may be block which are not in parent begin or child loop section and
	//      can still reach end section.
	//    * An additional PHI must be constructed on every path which is merging value from parent begin and child loop section.
	//      This must be done recursively also for new PHIs.
	//    * If block is dominated by child loop it should use only PHI in child header
	PHINode *phiInLatchDrivingBranch = nullptr;
	Value *valueForPhiInLatchCausingReenter = nullptr;
	//DTU.flush();
	BasicBlock *newLatchBlock;
	BasicBlock *oldLatchBlock;
	std::tie(newLatchBlock, oldLatchBlock) = prepareNewLatchBlock(mode, LParent,
			DTU, AR, MSSAU, phiInLatchDrivingBranch,
			valueForPhiInLatchCausingReenter, header, childPreHeader);
#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++)
					+ "-after-prepareNewLatchBlock.dot", AR.BFI, AR.BPI);
#endif
	//DTU.flush();
	// reroute all continue edges in child loop to jump to newLatchBlock
	// with value asserting that it will jump to parent loop header
	rerouteChildBackedgeAndTransferChildPhis(mode, childPreHeader, childHeader,
			header, LChild, oldLatchBlock, newLatchBlock, header, LParent,
			phiInLatchDrivingBranch, valueForPhiInLatchCausingReenter,
			*isChildLoop, associatedPhis, MSSAU, DTU);
#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++)
					+ "-after-rerouteChildBackedgeAndTransferChildPhis.dot",
			AR.BFI, AR.BPI);
#endif

	if (DTU.hasPendingUpdates())
		DTU.flush();

	Function *F = nullptr;
	if (tmpAllocas.size()) {
		F = tmpAllocas[0]->getParent()->getParent();
	}
	// construct PHIs for variables defined in loop begin section which are now alive trough iteration
	// of parent loop because it was merged with child loop
	PromoteMemToReg(tmpAllocas, DTU.getDomTree(), &AR.AC);
	if (tmpAllocas.size()) {
		for (auto &BB: *F) {
			// :note: llvm-21 PromoteMemToReg somehow generates phis with reversed order of operands according to block predecessors
			sortPhiOperands(BB);
		}
	}
	//promoteAllocasForBeginSectionLiveouts(beginSectionBegin, beginSectionEnd,
	//		LParent, DTU, AR);
	mergeNestedLoops(AR.LI, &AR.SE, LPMU, &LChild, &LParent);
#ifdef LoopFlattenUsingIfPass_TRACE
	writeCFGToDotFile(*LParent.getHeader()->getParent(),
			"LoopFlattenUsingIfPass." + std::to_string(dbgCntr++) + "-end.dot",
			AR.BFI, AR.BPI);
#endif
	Changed = true;
	sortPhiOperands(*childHeader);
	sortPhiOperands(*newLatchBlock);

	return Changed;
}

llvm::PreservedAnalyses LoopFlattenUsingIfPass::run(llvm::Loop &L,
		llvm::LoopAnalysisManager &AM, llvm::LoopStandardAnalysisResults &AR,
		llvm::LPMUpdater &U) {
	auto passMode = getOptionalStringHwtHlsLoopAttribute(&L,
			METADATANAME_MODE);
	bool Changed = false;
	if (passMode.has_value()) {
		assert(
				L.isRecursivelyLCSSAForm(AR.DT, AR.LI)
						&& "Requested to preserve LCSSA, but it's already broken.");
		//auto &F = *L.getHeader()->getParent();
		std::optional<MemorySSAUpdater> MSSAU;
		if (AR.MSSA)
			MSSAU = MemorySSAUpdater(AR.MSSA);

		DomTreeUpdater DTU(AR.DT, DomTreeUpdater::UpdateStrategy::Lazy);
		auto parentLoop = L.getParentLoop();
		if (!parentLoop) {
			throw std::runtime_error("LoopFlattenUsingIfPass enabled in a loop without parent (no parent to flatten this loop into)");
		}
		mergeLlvmLoopMd(L, *parentLoop);
		//errs() << "LoopFlattenUsingIfPass before: \n";
		//F.getParent()->dump();
		auto mode = modeStringToMode(passMode.value());
		Changed |= LoopFlattenUsingIfPass_flatten(mode, *parentLoop, L, AR, DTU,
				MSSAU ? &*MSSAU : nullptr, U);

		if (Changed) {
			// errs() << "LoopFlattenUsingIfPass after: \n";
			// F.dump();
			//assert(!verifyFunction(F, &errs()));
			U.markLoopNestChanged(true);
		}
		for (auto &L0 : AR.LI) {
			L0->verifyLoop();
		}
	}
	if (!Changed)
		return PreservedAnalyses::all();

	if (AR.MSSA && VerifyMemorySSA)
		AR.MSSA->verifyMemorySSA();
	PreservedAnalyses PA;
	return PA;
}

}
