[build-system]
requires = [
   "wheel",
   "meson>=0.60.1",
   "mesonpep517",
   "pybind11>=2.8.1",
   "ninja",
]
build-backend = "mesonpep517.buildapi"


[tool.mesonpep517.metadata]
author="Michal Orsak"
author-email="Nic30original@gmail.com"
summary="LLVM based HLS compiler"
requires  = [
   'hwtLib>=2.9',
   'scipy>=1.5.2',
   'networkx',
   'plotly',
   'pydot',
]
home-page="https://github.com/Nic30/hwtHls"
requires-python="py3"
description-file="README.md"
platforms="any"
classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
        "Topic :: System :: Hardware",
        "Topic :: System :: Emulators",
        "Topic :: Utilities"
]
