version: 2.1

orbs:
  python: circleci/python@0.2.1
  py: nic30/python-all-in-1@0.2.48

jobs:
  install-test-deploy:
    executor: python/default
    resource_class: small
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install build-essential python3-dev llvm-11-dev -y
      # - python/load-cache
      - py/install-package-git:
          cwd: ..
          url: https://github.com/Nic30/hwtHls
      - py/install-setup-py
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - install-test-deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
