version: 2.1

orbs:
  python: circleci/python@1.5.0
  py: nic30/python-all-in-1@0.2.48

jobs:
  install-test-deploy:
    machine:
      image: ubuntu-2204:2022.04.1
      python:
        version: 3.10.0
    #docker:
    #  - image: ubuntu:rolling
    resource_class: large
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            # because of tzdata
            export DEBIAN_FRONTEND=noninteractive
            export TZ=America/USA
            sudo apt install build-essential python3-dev llvm-14-dev python3 python3-pip git ninja-build cmake libreadline8 libreadline-dev -y
            pip3 install pip meson --upgrade
            # because of coverage (tool named coverage)
            echo 'export PATH=$PATH:/root/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          command: |
            whereis pip
            pip --version
            whereis python
            python --version

      # - python/load-cache
      - py/install-setup-py:
          build-args: "--verbose --progress-bar off"
         #no_output_timeout: 30m
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - install-test-deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
