version: 2.1

orbs:
  python: circleci/python@1.5.0
  py: nic30/python-all-in-1@0.2.48

jobs:
  install-test-deploy:
    docker:
      - image: ubuntu:rolling
    resource_class: large
    steps:
      - checkout
      - run:
          command: |
            apt update
            # because of tzdata
            export DEBIAN_FRONTEND=noninteractive
            export TZ=America/USA
            apt install build-essential python3-dev llvm-14-dev python3 python3-pip git ninja-build cmake libreadline8 libreadline-dev -y
            pip3 install pip meson --upgrade
            # because of coverage (tool named coverage)
            echo 'export PATH=$PATH:/root/.local/bin' >> $BASH_ENV
            update-alternatives --install /usr/bin/python python /usr/bin/python3 1
            source $BASH_ENV


      # - python/load-cache
      - py/install-setup-py:
          build-args: "--verbose --progress-bar off"
         #no_output_timeout: 30m
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - install-test-deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
