version: 2.1

orbs:
  python: circleci/python@2.0.3
  py: nic30/python-all-in-1@0.3.0

jobs:
  install-test-deploy:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            # because of tzdata
            export DEBIAN_FRONTEND=noninteractive
            export TZ=America/USA
            sudo apt install build-essential python3-dev llvm-16-dev python3 python3-pip python3-venv git ninja-build cmake libreadline8 libreadline-dev -y
            python3 -m venv --system-site-packages /opt/circleci/.pyenv3
            echo 'source /opt/circleci/.pyenv3/bin/activate' >> $BASH_ENV
            source /opt/circleci/.pyenv3/bin/activate
            pip3 install pip meson --upgrade
            
      - run:
          command: |
            echo $PATH
            whereis pip
            pip --version
            whereis python
            python --version
            whereis virtualenv
            meson --version

      # - python/load-cache
      - py/install-setup-py:
          build-args: "--verbose --progress-bar off"
         #no_output_timeout: 30m
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - install-test-deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
