version: 2.1

orbs:
  python: circleci/python@3.3.0
  py: nic30/python-all-in-1@0.3.1

jobs:
  prepare-workspace:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    steps:
      - run:
          command: |
            apt update
            # because of tzdata
            echo "export DEBIAN_FRONTEND=noninteractive" >> "$BASH_ENV"
            echo "export TZ=America/USA" >> "$BASH_ENV"
            source "$BASH_ENV"
            apt install git -y
            export ABC_VERSION_LATEST=$(git ls-remote https://github.com/berkeley-abc/abc.git HEAD | awk '{ print $1}')
            echo "Info: last ABC version is $ABC_VERSION_LATEST"
            echo "export ABC_VERSION_LATEST=$ABC_VERSION_LATEST" >> "$BASH_ENV"
            source "$BASH_ENV"
            # https://support.circleci.com/hc/en-us/articles/10816400480411-How-to-pass-environment-variables-between-jobs
            cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  berkeley-abc-prebuild:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - attach_workspace:
         at: .
      - run: |
          cat bash.env >> $BASH_ENV
          source "$BASH_ENV"
          rm bash.env
          echo $ABC_VERSION_LATEST > abc.version

      - restore_cache:
          name: Restore libabc-dev Package Cache
          keys:
            - libabc-dev-{{ checksum "abc.version" }} # must use checksum of checksum because circleci does not allow access to generated variables using {{ .Environment.var }}
      - run:
          command: |
            ABC_BUILD_CACHE_KEY=$(cksum --base64 --untagged --quiet -a sha256 abc.version | cut -d ' ' -f 1) # same as checksum "abc.version"
            echo "expected ABC_BUILD_CACHE_KEY=$ABC_BUILD_CACHE_KEY"
            if [ ! -f "subprojects/DEB/libabc-dev-$ABC_BUILD_CACHE_KEY-Linux.deb" ]; then
              echo "Building libabc-dev deb because it was not found in cache (ABC_VERSION_LATEST=$ABC_VERSION_LATEST, cache_hash=$ABC_BUILD_CACHE_KEY)"
              cd subprojects
              apt update
              apt install build-essential git ninja-build cmake libreadline8 libreadline-dev -y
              ./build_debs.sh
			  cd $CIRCLE_WORKING_DIRECTORY/hwtHls/subprojects/DEB
              mv libabc-dev-$ABC_VERSION_LATEST-Linux.deb libabc-dev-$ABC_BUILD_CACHE_KEY-Linux.deb 
              ls -l $CIRCLE_WORKING_DIRECTORY/hwtHls/subprojects/DEB
            fi
      - save_cache:
         name: Save libabc-dev Package Cache
         key: libabc-dev-{{ checksum "abc.version" }}
         paths:
           - hwtHls/subprojects/DEB/libabc-dev-{{ checksum "abc.version" }}-Linux.deb
      
  install-test-deploy:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    executor:
       name: python/default
       tag: "3.13.7"
    steps:
      - checkout
      - attach_workspace:
         at: .
      - run: |
          cat bash.env >> $BASH_ENV
          source "$BASH_ENV"
          rm bash.env
          echo $ABC_VERSION_LATEST > abc.version

      - restore_cache:
          name: Restore libabc-dev Package Cache
          keys:
            - libabc-dev-{{ checksum "abc.version" }}
      - run:
          command: |
            apt update
            apt install build-essential python3-dev llvm-18-dev python3 python3-pip python3-venv git ninja-build cmake libreadline8 libreadline-dev -y
            dpkg -i subprojects/DEB/libabc-dev-$ABC_VERSION_LATEST-Linux.deb
            python3 -m venv --system-site-packages /opt/circleci/.pyenv3
            echo 'source /opt/circleci/.pyenv3/bin/activate' >> $BASH_ENV
            source /opt/circleci/.pyenv3/bin/activate
            pip3 install pip meson --upgrade
            pip3 install concurrencytest

      - run:
          command: |
            echo $PATH
            whereis pip
            pip --version
            whereis python
            python --version
            whereis virtualenv
            meson --version

      # - python/load-cache
      # https://mesonbuild.com/meson-python/how-to-guides/debug-builds.html -Csetup-args=-Dbuildtype=debug
      - py/install-setup-py:
          build-args: "--verbose --progress-bar off -Csetup-args=-Dbuildtype=debug"
         #no_output_timeout: 30m
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - prepare-workspace
      - berkeley-abc-prebuild:
          requires:
            - prepare-workspace
      - install-test-deploy:
          requires:
            - berkeley-abc-prebuild
          context:
              - pypi
          filters:
            tags:
              only: /.*/
          