version: 2.1

orbs:
  python: circleci/python@3.3.0
  py: nic30/python-all-in-1@0.3.1

jobs:
  berkeley-abc-prebuild:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      - run:
          command: |
             echo "export ABC_VERSION_LATEST=$(git ls-remote $https://github.com/berkeley-abc/abc.git HEAD | awk '{ print $1}' | xargs git rev-parse --short)" >> "$BASH_ENV"
      - restore_cache:
          name: Restore libabc-dev Package Cache
          keys:
            - libabc-dev-{{ .Environment.ABC_VERSION_LATEST }}
      - run:
          command: |
            if [ ! -f "subprojects/DEB/libabc-dev-$ABC_VERSION_LATEST-Linux.deb" ]; then
              cd subprojects
              apt update
              # because of tzdata
              export DEBIAN_FRONTEND=noninteractive
              export TZ=America/USA
              apt install build-essential git ninja-build cmake libreadline8 libreadline-dev -y
              ./build_debs.sh
            fi
      - save_cache:
         name: Save libabc-dev Package Cache
         key: libabc-dev-{{ .Environment.ABC_VERSION_LATEST }}
         paths:
           - hwtHls/subprojects/DEB/libabc-dev-{{ .Environment.ABC_VERSION_LATEST }}-Linux.deb
      
  install-test-deploy:
    resource_class: large
    docker:
      - image: ubuntu:rolling
    executor:
       name: python/default
       tag: "3.13.7"
    steps:
      - checkout
      - run:
          command: |
             echo "export ABC_VERSION_LATEST=$(git ls-remote $https://github.com/berkeley-abc/abc.git HEAD | awk '{ print $1}' | xargs git rev-parse --short)" >> "$BASH_ENV"
      - restore_cache:
          name: Restore libabc-dev Package Cache
          keys:
            - libabc-dev-{{ .Environment.ABC_VERSION_LATEST }}
      - run:
          command: |
            apt update
            # because of tzdata
            export DEBIAN_FRONTEND=noninteractive
            export TZ=America/USA
            apt install build-essential python3-dev llvm-18-dev python3 python3-pip python3-venv git ninja-build cmake libreadline8 libreadline-dev -y
            dpkg -i subprojects/DEB/libabc-dev-$ABC_VERSION_LATEST-Linux.deb
            python3 -m venv --system-site-packages /opt/circleci/.pyenv3
            echo 'source /opt/circleci/.pyenv3/bin/activate' >> $BASH_ENV
            source /opt/circleci/.pyenv3/bin/activate
            pip3 install pip meson --upgrade
            pip3 install concurrencytest

      - run:
          command: |
            echo $PATH
            whereis pip
            pip --version
            whereis python
            python --version
            whereis virtualenv
            meson --version

      # - python/load-cache
      # https://mesonbuild.com/meson-python/how-to-guides/debug-builds.html -Csetup-args=-Dbuildtype=debug
      - py/install-setup-py:
          build-args: "--verbose --progress-bar off -Csetup-args=-Dbuildtype=debug"
         #no_output_timeout: 30m
      # - python/save-cache
      - py/test-and-coverage
      - py/deploy-pypi-on-tag:
          bin: false
          src: false
          build: true

workflows:
  main:
    jobs:
      - berkeley-abc-prebuild
      - install-test-deploy:
          requires:
            - berkeley-abc-prebuild
          context:
              - pypi
          filters:
            tags:
              only: /.*/
          