# :note: This is an example file
# :see: custom-llvm.ini
[binaries]
# equivalent of meson setup build -Dpython="..."
python = '/home/nic30/Documents/workspace/hwtHls-venv/bin/python'
# :note: This overrides only "Program python found: " in meson setup log, but there is also search for python
# c/c++ dependency for that the python must know where its source is.
# python3 -c "import sysconfig; print(sysconfig.get_config_var('INCLUDEPY')); print(sysconfig.get_config_var('LIBDIR'))"
# By defauilt the paths point to global installation
# If you are building cpython from sources you need to override the installation prefix
# ``` 
# ./configure --enable-optimizations --prefix="$PWD/build/installation"
# make -j"$(nproc)"
# make install
# ```
# :attention: if you build python with --with-pydebug it will set Py_C_RECURSION_LIMIT 500 instead of default 10k
